name: Java Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Checkstyle
      run: |
        sudo apt-get install -y checkstyle

    - name: Run Checkstyle
      run: |
        ./mvnw checkstyle:check
